# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imgur', '0002_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=30)),
                ('img_description', models.CharField(max_length=255)),
                ('img_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='DEFAULT VALUE', upload_to='imgur/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgur.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgur.Location'),
        ),
    ]
