# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imgur', '0004_auto_20190723_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=30)),
                ('img_description', models.CharField(max_length=255)),
                ('img_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='DEFAULT VALUE', upload_to='imgur/')),
                ('img_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgur.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='img_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgur.Location'),
        ),
    ]
