# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0006_auto_20190726_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=30)),
                ('img_description', models.CharField(max_length=255)),
                ('img_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='DEFAULT VALUE', upload_to='imgur/')),
                ('img_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgur.Category')),
                ('img_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgur.Location')),
            ],
        ),
    ]
